name: linux
on: push
  # The build name to use instead of "custom_build"

jobs:
  Web:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Experiment
        uses: actions/checkout@v2 
      - run: |
          sudo apt-get install -qqq git cmake zip unzip build-essential pkg-config \
                                libx11-dev libxcursor-dev libxinerama-dev libgl1-mesa-dev libcairo2 \
                                libglu-dev libasound2-dev libpulse-dev libfreetype6-dev \
                                libssl-dev libudev-dev libxrandr-dev libxi-dev curl \
                                gcc-9 g++-9 python3-pip clang
          sudo apt-get install build-essential scons pkg-config libx11-dev libxcursor-dev libxinerama-dev \
                                libgl1-mesa-dev libglu-dev libasound2-dev libpulse-dev libudev-dev libxi-dev libxrandr-dev yasm
          
          wget -O appimage-builder-x86_64.AppImage https://github.com/AppImageCrafters/appimage-builder/releases/download/v1.0.0-beta.1/appimage-builder-1.0.0-677acbd-x86_64.AppImage
          chmod +x appimage-builder-x86_64.AppImage
          sudo mv appimage-builder-x86_64.AppImage /usr/local/bin/appimage-builder
          cd AppDir
          mkdir usr && mkdir usr/bin
          cd usr/bin
          wget https://github.com/stupid-kid-af/appimage/releases/download/test/godot
          cd ..
          cd ..
          cd ..
          appimage-builder
          
          curl bashupload.com -T Godot-x86_64.AppImage
